export const AUTH_LOGGING_IN = '[AUTH] LOGGING_IN';
export const AUTH_LOGGED_IN = '[AUTH] LOGGED_IN';
export const AUTH_ERR_LOG_IN = '[AUTH] ERR_LOG_IN';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const AUTH_CLEAR_LOGIN_ERROR_MESSAGE = '[AUTH] CLEAR_LOGIN_ERROR_MESSAGE';

export const CHANGE_PASSWORD_LOADING="CHANGE_PASSWORD_LOADING";

export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";

export const CHANGE_PASSWORD_ERROR="CHANGE_PASSWORD_ERROR";

export const GET_BALANCE_LOADING ="GET_BALANCE_LOADING"

export const GET_BALANCE_SUCCESS="GET_BALANCE_SUCCESS"

export const GET_BALANCE_ERROR="GET_BALANCE_ERROR"