export const FETCH_SUCCESS ='FETCH_SUCCESS';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR ='CLEAR_ERROR';
export const FETCH_TRANS ='FETCH_TRANS';
export const FETCH_STARTTIMES ='FETCH_STARTTIMES';
export const FETCH_MULTICHOICE ='FETCH_MULTICHOICE'
export const CLEAR_SATALLITE_ERROR ='CLEAR_ERROR';
export const SET_MULTICHOICE_ERROR = 'SET_MULTICHOICE_ERROR';
export const LOADING_SATALLITE ="LOADING_SATALLITE"
export const SET_STARTIMES_ERROR = 'SET_STARTIMES_ERROR';
export const MULTICHOICE_VENDING_SUCCESS="MULTICHOICE_VENDING_SUCCESS";
export const MULTICHOICE_VENDING_LOADING="MULTICHOICE_VENDING_LOADING";
export const MULTICHOICE_VENDING_ERROR="MULTICHOICE_VENDING_ERROR";
export const FETCH_AIRTIME_SUCCESS ='FETCH_SUCCESS';

export const STARTIME_VENDING_SUCCESS="STARTIME_VENDING_SUCCESS";
export const STARTIME_VENDING_LOADING="STARTIME_VENDING_LOADING";
export const STARTIME_VENDING_ERROR="STARTIME_VENDING_ERROR";


export const AIRTIME_VENDING_SUCCESS="AIRTIME_VENDING_SUCCESS";
export const AIRTIME_VENDING_LOADING="AIRTIME_VENDING_LOADING";
export const AIRTIME_VENDING_ERROR="AIRTIME_VENDING_ERROR";

export const DATA_VENDING_SUCCESS="DATA_VENDING_SUCCESS";
export const DATA_VENDING_LOADING="DATA_VENDING_LOADING";
export const DATA_VENDING_ERROR="DATA_VENDING_ERROR";

export const PAYMENT_SUCCESS="PAYMENT_SUCCESS";
export const PAYMENT_LOADING="PAYMENT_LOADING"

export const ELECTRICITY_VALIDATION_LOADING="ELECTRICITY_VALIDATION_LOADING"

export const VERIFY_PAYSTACK_SUCCESS="VERIFY_PAYSTACK_SUCCESS"

export const VERIFY_PAYSTACK_ERROR="VERIFY_PAYSTACK_ERROR"

export const BANK_TRANSFER_SUCCESS="BANK_TRANSFER_SUCCESS";
export const BANK_TRANSFER_LOADING="BANK_TRANSFER_LOADING";
export const BANK_TRANSFER_ERROR="BANK_TRANSFER_ERROR";
export const NOTIFICATION_SUCCESS="NOTIFICATION_SUCCESS"